replicaCount: 1

image:
  repository: ghcr.io/wingorithm/k8s-cluster-components/service-log
  pullPolicy: Always
  tag: "release-dev"

service:
  type: ClusterIP
  port: 8081
  name: logservice-k8s
environment:
  namespace: development

#note that :
#100Mi ~ 100MiB ~ 104 MB (megabyte) ~ 0.1 GB
#1000m (millicore) ~ 100% of 1 full core cpu time
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 384Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
#  targetMemoryUtilizationPercentage: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # Wait only 30 sec to wait (stable ?= scaledown)
      policies:
        - type: Pods
          value: 3
          periodSeconds: 15 # Allow killing 1 pods every 15s (very aggressive)