replicaCount: 1

image:
  repository: ghcr.io/wingorithm/k8s-cluster-components/a_service
  pullPolicy: Always
  tag: "release-dev"

service:
  type: ClusterIP
  port: 8082
  name: a-service-k8s
environment:
  namespace: development

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 384Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 3
          periodSeconds: 15