server.port=8082
spring.application.name=a_service
logging.pattern.console=%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX},UTC+7} | ${LOG_LEVEL_PATTERN:%5p} | [%15.15t] | ${PID:- } | %-40.40logger{39} | %X{traceId:-} | %X{spanId:-} | %X{requestId:-} | %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
logging.pattern.file=%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX},UTC+7} | ${LOG_LEVEL_PATTERN:%5p} | [%15.15t] | ${PID:- } | %-40.40logger{39} | %X{traceId:-} | %X{spanId:-} | %X{requestId:-} | %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
management.endpoint.health.probes.enabled=true

spring.datasource.url=jdbc:postgresql://my-postgresql.default.svc.cluster.local:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=hLkZ6WiyGh
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

url.logservice=http://logservice-k8s.development.svc.cluster.local:8081
url.b-service=http://b_service.development.svc.cluster.local:8083